---
socat_name: socat

socat_bind_type:
socat_bind_interface:
socat_bind_opts:
socat_bind: >-
  {{ socat_bind_type }}:{{ socat_bind_interface }}
  {%- if socat_bind_opts -%}
  ,{{ socat_bind_opts }}
  {%- endif -%}

socat_connect_type:
socat_connect_interface:
socat_connect_opts:
socat_connect: >-
  {{ socat_connect_type }}:{{ socat_connect_interface }}
  {%- if socat_connect_opts -%}
  ,{{ socat_connect_opts }}
  {%- endif -%}
