---
dependency:
  name: galaxy
driver:
  name: molecule-qemu
platforms:
  - name: debian-bullseye-arm64
    image_arch: aarch64
    image_url: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-arm64.qcow2
    image_checksum: sha512:https://cloud.debian.org/images/cloud/bullseye/latest/SHA512SUMS
provisioner:
  name: ansible
  inventory:
    host_vars:
      debian-bullseye-arm64:
        socat_name: socat@proxy
        socat_bind_type: tcp4-listen
        socat_bind_interface: 8000
        socat_bind_opts: fork,reuseaddr
        socat_connect_type: socks4a:127.0.0.1
        socat_connect_interface: example.com:80
        socat_connect_opts: socksport=1080

verifier:
  name: testinfra
